/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casacambio;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marcos
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoColcaoDolar = new javax.swing.JLabel();
        ultimoValorDolar = new javax.swing.JLabel();
        dataUltimoDolar = new javax.swing.JLabel();
        textoCotacaoEuro = new javax.swing.JLabel();
        ultimoValorEuro = new javax.swing.JLabel();
        dataUltimoEuro = new javax.swing.JLabel();
        textoPesquisar = new javax.swing.JLabel();
        selecaoMoeda = new javax.swing.JComboBox<String>();
        dataPesquisa = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCotacao = new javax.swing.JMenu();
        mHistorico = new javax.swing.JMenu();
        mConversao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        textoColcaoDolar.setForeground(new java.awt.Color(63, 81, 181));
        textoColcaoDolar.setText("Última cotação do dolar:");

        ultimoValorDolar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ultimoValorDolar.setForeground(new java.awt.Color(63, 81, 181));
        ultimoValorDolar.setText("R$ 3,25");

        dataUltimoDolar.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        dataUltimoDolar.setForeground(new java.awt.Color(63, 81, 181));
        dataUltimoDolar.setText("15/09/2016 ás 16:00");

        textoCotacaoEuro.setForeground(new java.awt.Color(255, 87, 34));
        textoCotacaoEuro.setText("Última cotação do Euro:  ");

        ultimoValorEuro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ultimoValorEuro.setForeground(new java.awt.Color(255, 87, 34));
        ultimoValorEuro.setText("R$ 3,60");

        dataUltimoEuro.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        dataUltimoEuro.setForeground(new java.awt.Color(255, 87, 34));
        dataUltimoEuro.setText("15/09/2016 ás 16:00");

        textoPesquisar.setText("Pesquisar: ");

        selecaoMoeda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Dólar", "Euro" }));
        selecaoMoeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecaoMoedaActionPerformed(evt);
            }
        });

        dataPesquisa.setText("00/00/0000");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Data:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textoColcaoDolar)
                                .addGap(18, 18, 18)
                                .addComponent(ultimoValorDolar))
                            .addComponent(dataUltimoDolar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textoCotacaoEuro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ultimoValorEuro))
                            .addComponent(dataUltimoEuro))
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnPesquisar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(textoPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selecaoMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dataPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPesquisar)
                    .addComponent(selecaoMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoColcaoDolar)
                    .addComponent(ultimoValorDolar)
                    .addComponent(ultimoValorEuro)
                    .addComponent(textoCotacaoEuro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataUltimoDolar)
                    .addComponent(dataUltimoEuro))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        mCotacao.setText("Cotação atual");
        jMenuBar1.add(mCotacao);

        mHistorico.setText("Histórico");
        mHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mHistoricoMouseClicked(evt);
            }
        });
        mHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHistoricoActionPerformed(evt);
            }
        });
        jMenuBar1.add(mHistorico);

        mConversao.setText("Conversão");
        mConversao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mConversaoMouseClicked(evt);
            }
        });
        jMenuBar1.add(mConversao);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("BarraMenu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecaoMoedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecaoMoedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoMoedaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        Cotacoes cotacoes = new Cotacoes();
        URL url;
        System.out.println(dataPesquisa.getText());
        if(selecaoMoeda.getSelectedItem() == "Dólar")
        {
            try {
                url = new URL("http://localhost/Dolar.csv");
                cotacoes.lerCotacao(url);
            } catch (MalformedURLException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(selecaoMoeda.getSelectedItem() == "Euro")
        {
              try {
                url = new URL("http://localhost/Euro.csv");
                cotacoes.lerCotacao(url);
            } catch (MalformedURLException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void mConversaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mConversaoMouseClicked
        new TelaConversao().setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_mConversaoMouseClicked

    private void mHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mHistoricoActionPerformed

    private void mHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mHistoricoMouseClicked
       
    }//GEN-LAST:event_mHistoricoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JFormattedTextField dataPesquisa;
    private javax.swing.JLabel dataUltimoDolar;
    private javax.swing.JLabel dataUltimoEuro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mConversao;
    private javax.swing.JMenu mCotacao;
    private javax.swing.JMenu mHistorico;
    private javax.swing.JComboBox<String> selecaoMoeda;
    private javax.swing.JLabel textoColcaoDolar;
    private javax.swing.JLabel textoCotacaoEuro;
    private javax.swing.JLabel textoPesquisar;
    private javax.swing.JLabel ultimoValorDolar;
    private javax.swing.JLabel ultimoValorEuro;
    // End of variables declaration//GEN-END:variables
}
